echo response

diff --git a/.github/workflows/create_repo.yml b/.github/workflows/create_repo.yml
--- a/.github/workflows/create_repo.yml
+++ b/.github/workflows/create_repo.yml
@@ -23,18 +23,21 @@ jobs:
           ORG_NAME="Maua-Dev"
 
           # Fetch user membership information
-          response=$(curl -s -H "Authorization: Bearer ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}" \
-            "https://api.github.com/orgs/$ORG_NAME/members/$USERNAME")
+          # response=$(curl -s -H "Authorization: Bearer ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}" \
+          #   "https://api.github.com/orgs/$ORG_NAME/members/$USERNAME")
           
+          response=$(gh api /orgs/$ORG_NAME/members/$USERNAME)
+
           echo "Response: $response"
 
-          # Check if the user is a member of the organization
-          if [[ $(echo "$response" | jq -r .message) == "Not Found" ]]; then
-            echo "User '$USERNAME' is not a member of the organization."
-            exit 1
-          else
-            echo "User '$USERNAME' is a member of the organization."
-          fi
+
+          # # Check if the user is a member of the organization
+          # if [[ $(echo "$response" | jq -r .message) == "Not Found" ]]; then
+          #   echo "User '$USERNAME' is not a member of the organization."
+          #   exit 1
+          # else
+          #   echo "User '$USERNAME' is a member of the organization."
+          # fi
           
       - name: Check if issue title starts with [NEW_REPO]
         if: startsWith(github.event.issue.title, '[NEW_REPO]')
